[package]
name = "failed-auth-rs"
version = "0.1.0"
authors = ["jk977"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.8"
ipnet = "2.3"
log = "0.4"
serde_json = "1.0"
