[package]
name = "cloudcheck"
version = "0.1.0"
authors = ["jk977"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipnet = "~2.3.0"
serde_json = "~1.0.61"
clap = "~2.33.3"
